name: CI/CD Pipeline for AWS Lambda ETL

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/

  build:
    name: Package Lambda Function
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r requirements.txt -t package/

      - name: Zip Lambda Function
        run: |
          cp src/lambda_function.py package/
          cd package && zip -r ../lambda_function.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda-package
          path: lambda_function.zip

  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda-package
          path: .

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          command: aws lambda update-function-code --function-name MyETLFunction --zip-file fileb://lambda_function.zip
